# Site
name: '실감 팀 블로그'
title: '실감 팀 블로그'
description: '수능 필수 앱이 되기까지 실감 팀의 여정'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
disqus:
mailchimp-list:
include: ['_pages']
permalink: /:title/

# Authors
authors:
  민승현:
    name: 민승현
    display_name: 민승현
    avatar: 'assets/images/seunghyun.jpg'
    gravatar:
    email: seunghyun@silgam.app
    web: https://www.linkedin.com/in/seunghyunmin/
    twitter: https://www.linkedin.com/in/seunghyunmin/
    description: '실감의 founder로, 실감을 개발하고 팀을 이끌고 있습니다.'
  강용진:
    name: 강용진
    display_name: 강용진
    avatar: 'assets/images/yongjin.png'
    gravatar:
    email: yongjin@silgam.app
    web: https://www.instagram.com/self_educator
    twitter: https://www.instagram.com/self_educator
    description: '실감의 co-founder로, 사업개발을 맡고 있습니다.'
  실감:
    name: 실감
    display_name: 실감
    avatar: 'assets/images/silgam.png'
    gravatar:
    email: contact@silgam.app
    web: https://silgam.app
    twitter: https://silgam.app/instagram
    description: '수능 시뮬레이션부터 성적 관리까지, 수능 필수 앱 실감'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 12
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: 'disabled'
adsense-data-ad-client:
adsense-data-ad-slot:

# Lazy Images ("enabled" or "disabled")
lazyimages: 'enabled'

exclude:
  [
    changelog.md,
    LICENSE.txt,
    README.md,
    Gemfile,
    Gemfile.lock,
    CNAME,
    docker-compose.yml,
  ]
